"use client";

// Warm-up set marker: amber "W" chip used wherever sets are listed, so ramp
// sets generated by the warm-up popover (or tagged by hand) stay visually
// distinct from working sets.
import { cn } from "@/lib/utils";

export function WarmupBadge({ className, label = "W" }: { className?: string; label?: string }) {
  return (
    <span
      className={cn(
        "inline-flex items-center justify-center rounded-md bg-amber-500/15 font-black text-amber-600 dark:text-amber-400",
        "h-6 w-6 text-[11px]",
        className,
      )}
      aria-label="warm-up set"
      title="Warm-up set"
    >
      {label}
    </span>
  );
}
