// ─────────────────────────────────────────────────────────────────────────────
// The generated tour registry (single runtime import point).
//
// Generated by `bun run tour:gen` (scripts/tour-gen.ts) from inline
// declarations — NEVER hand-edit src/generated/tour-registry.json.
// Screen id === route name (src/features/shell/router.ts), 1:1.
// ─────────────────────────────────────────────────────────────────────────────

import raw from "@/generated/tour-registry.json";
import type { TourRegistry } from "@/lib/tour/types";

export const registry = raw as unknown as TourRegistry;

/** Synthetic screenId under which the welcome tour's outcome is recorded. */
export const WELCOME_KEY = "__welcome";

/** Screens where tours/hints never auto-start. */
export const NO_TOUR_SCREENS = new Set(["auth", "onboarding", "dev"]);
